#version: "3"
#
#services:
#  # Postgres
#  db:
#    image: postgres
#    environment:
#      - POSTGRES_USER=canadiyaman
#      - POSTGRES_DB=thetask
#  web:
#    volumes:
#      - /usr/src/app
#    environment:
#      - DATABASE_URL=postgres://postgres:canadiyaman@postgres:5432/thetask
#      - PG_HOST=postgres
#      - PG_PORT=5432
#      - DEBUG=1
#      - SECRET_KEY=${SECRET_KEY}
#    build: .
#    ports:
#      - "8000:8000"
#    depends_on:
#    - db
version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=thetask
volumes:
  postgres_data:
